<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Product_fdfds</name>
   <tag></tag>
   <elementGuidId>807cd8f5-19c7-474f-8451-938fddb02c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[3]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'http://res.cloudinary.com/dgaeremr2/image/upload/v1670226491/Products-Customers/xk24ziubafhevdtddxbl.png' and @alt = 'Product fdfds']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a29a84e-badf-4228-b012-6cef6a616640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://res.cloudinary.com/dgaeremr2/image/upload/v1670226491/Products-Customers/xk24ziubafhevdtddxbl.png</value>
      <webElementGuid>740bf6d7-dfdb-4138-895f-81e7e3e57706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>e2cfb602-5b84-489a-9f71-04c223f9ccc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Product fdfds</value>
      <webElementGuid>867197e0-4fa8-467b-9a86-944eb97823e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;mt-4 pb-4 container&quot;]/div[@class=&quot;mt-4 row&quot;]/div[@class=&quot;col-lg-9 col&quot;]/div[@class=&quot;row row-cols-lg-3&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;content card&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>984139ff-879f-49ae-b8e9-6ed170685f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[3]/div/img</value>
      <webElementGuid>b83c7b51-057b-4586-b61c-1e659006b918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Product fdfds']</value>
      <webElementGuid>621dd501-b09d-44cb-93b0-b2a32d100d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>3120c9b4-f901-4632-8c4d-b4194223832c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://res.cloudinary.com/dgaeremr2/image/upload/v1670226491/Products-Customers/xk24ziubafhevdtddxbl.png' and @alt = 'Product fdfds']</value>
      <webElementGuid>75a0b2e3-1c3e-4a37-a5c4-78b1c4d1adb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
